vich_uploader:
    db_driver: orm

    mappings:
        evenements_images:
            uri_prefix: assets/image/evenements
            upload_destination: '%kernel.project_dir%/public/assets/image/evenements'
        photos_images:
            uri_prefix: assets/image/photos
            upload_destination: '%kernel.project_dir%/public/assets/image/photos'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
