#index:
#    path: /
#    controller: App\Controller\DefaultController::index


accueil:
  path: /accueil
  controller: App\Controller\HomeController::index

evenements:
  path: /evenements
  controller: App\Controller\EventsController::index

boutique:
  path: /boutique
  controller: App\Controller\ShopController::index

photos:
  path: /photos
  controller: App\Controller\PhotosController::index