#index:
#    path: /
#    controller: App\Controller\DefaultController::index


accueil:
  path: /accueil
  controller: App\Controller\HomeController::index

#les chemins relatifs aux événements

evenements:
  path: /evenements/accueil
  controller: App\Controller\EventsController::index

evenementId:
  path: /evenements/{id}/description
  controller: App\Controller\EventsController::show

evenementsAll:
  path: /evenements/tous
  controller: App\Controller\EventsController::all

evenementsMois:
  path: /evenements/mois
  controller: App\Controller\EventsController::month

evenementsPerso:
  path: /evenements/mes_evenements
  controller: App\Controller\EventsController::my


#chemin relatif à la législation

legislation:
  path: /legislation
  controller: App\Controller\HomeController::legislation


#chemins relatifs à la boutique

boutique/accueil:
  path: /boutique/accueil
  controller: App\Controller\ShopController::index

boutique/produits:
  path: /boutique/tous-nos-produits
  controller: App\Controller\ShopController::tousProduits

boutique/categorie/habits:
  path: /boutique/habits
  controller: App\Controller\ShopController::habits

boutique/categorie/produits-IT:
  path: /boutique/produits-IT
  controller: App\Controller\ShopController::produitsIT

boutique/categorie/goodies:
  path: /boutique/goodies
  controller: App\Controller\ShopController::goodies

boutique/categorie/reductions:
  path: /boutique/reduction
  controller: App\Controller\ShopController::reduction

boutique/ID:
  path: boutique/{ID}/description
  controller: App\Controller\ShopController::show

photos:
  path: /photos
  controller: App\Controller\PhotosController::index

