#index:
#    path: /
#    controller: App\Controller\DefaultController::index


accueil:
  path: /accueil
  controller: App\Controller\HomeController::index

#les chemins relatifs aux événements

evenements:
  path: /evenements/accueil
  controller: App\Controller\EventsController::index

evenementId:
  path: /evenements/{id}/description
  controller: App\Controller\EventsController::show

evenementsAll:
  path: /evenements/tous
  controller: App\Controller\EventsController::all

evenementsMois:
  path: /evenements/mois
  controller: App\Controller\EventsController::month

evenementsPerso:
  path: /evenements/mes_evenements
  controller: App\Controller\EventsController::my

evenementsRegisterId:
  path: /evenements/{id}/register
  controller: App\Controller\EventsController::register

#chemin relatif à la législation

legislation:
  path: /legislation
  controller: App\Controller\HomeController::legislation


#chemins relatifs à la boutique

boutique/accueil:
  path: /boutique/accueil
  controller: App\Controller\ShopController::index

boutique/produits:
  path: /boutique/tous-nos-produits
  controller: App\Controller\ShopController::all

boutique/categorie/habits:
  path: /boutique/habits
  controller: App\Controller\ShopController::habits

boutique/categorie/produits-IT:
  path: /boutique/produits-IT
  controller: App\Controller\ShopController::produitsIT

boutique/categorie/goodies:
  path: /boutique/goodies
  controller: App\Controller\ShopController::goodies

boutique/categorie/reductions:
  path: /boutique/reduction
  controller: App\Controller\ShopController::reduction

administration:
  path: /administration
  controller: App\Controller\Admin\AdminHomeController::index

boutique/ID:
  path: boutique/{ID}/description
  controller: App\Controller\ShopController::show
  #options: {"mapping" : {"id" : "id"}}

adminEventsHome:
  path: /administration/evenements
  controller: App\Controller\Admin\AdminEventsController::index

adminEventsAdd:
  path: /administration/evenements/add
  controller: App\Controller\Admin\AdminEventsController::add

adminEventsEdit:
  path: /administration/evenements/edit/{id}
  controller: App\Controller\Admin\AdminEventsController::edit

adminEventsDelete:
  path: /administration/evenements/delete/{id}
  controller: App\Controller\Admin\AdminEventsController::delete

adminCategoryHome:
  path: /administration/categories
  controller: App\Controller\Admin\AdminCategoryController::index

adminCategoryAdd:
  path: /administration/categories
  controller: App\Controller\Admin\AdminCategoryController::add

adminCategoryEdit:
  path: /administration/categories/edit/{id}
  controller: App\Controller\Admin\AdminCategoryController::edit

adminCategoryDelete:
  path: /administration/categories/delete/{id}
  controller: App\Controller\Admin\AdminCategoryController::delete

#boutique/categorie/index:
  #path: /boutique/accueil
  #controller: App\Controller\ShopController::index

#boutique/categorie/{nom}:
  #path: /boutique/{nom}
  #controller: App\Controller\ShopController::categorie

photos:
  path: /photos
  controller: App\Controller\PhotosController::index

