#index:
#    path: /
#    controller: App\Controller\DefaultController::index


accueil:
  path: /accueil
  controller: App\Controller\HomeController::index

evenements:
  path: /evenements/accueil
  controller: App\Controller\EventsController::index

evenementId:
  path: /evenements/{id}/description
  controller: App\Controller\EventsController::show

evenementsAll:
  path: /evenements/tous
  controller: App\Controller\EventsController::all

legislation:
  path: /legislation
  controller: App\Controller\HomeController::legislation

evenementsMois:
  path: /evenements/mois
  controller: App\Controller\EventsController::month

evenementsPerso:
  path: /evenements/mes_evenements
  controller: App\Controller\EventsController::my

boutique/accueil:
  path: /boutique/accueil
  controller: App\Controller\ShopController::index

boutique/produits:
  path: /boutique/tous-nos-produits
  controller: App\Controller\ShopController::tousProduits

boutique/categorie/habits:
  path: /boutique/habits
  controller: App\Controller\ShopController::habits

boutique/categorie/produits-IT:
  path: /boutique/produits-IT
  controller: App\Controller\ShopController::produitsIT

boutique/categorie/goodies:
  path: /boutique/goodies
  controller: App\Controller\ShopController::goodies

boutique/categorie/reductions:
  path: /boutique/reduction
  controller: App\Controller\ShopController::reduction

adminEventsHome:
  path: /administration/evenements
  controller: App\Controller\Admin\AdminEventsController::index

adminEventsAdd:
  path: /administration/evenements/add
  controller: App\Controller\Admin\AdminEventsController::add

adminEventsEdit:
  path: /administration/evenements/edit/{id}
  controller: App\Controller\Admin\AdminEventsController::edit

adminEventsDelete:
  path: /administration/evenements/delete/{id}
  controller: App\Controller\Admin\AdminEventsController::delete

#boutique/categorie/index:
  #path: /boutique/accueil
  #controller: App\Controller\ShopController::index

#boutique/categorie/{nom}:
  #path: /boutique/{nom}
  #controller: App\Controller\ShopController::categorie

photos:
  path: /photos
  controller: App\Controller\PhotosController::index

security_connexion:
  path: /connexion
  controller: App\Controller\SecurityController::login

security_inscription:
  path: /inscription
  controller: App\Controller\SecurityController::inscription
