#index:
#    path: /
#    controller: App\Controller\DefaultController::index


accueil:
  path: /
  controller: App\Controller\HomeController::index

#les chemins relatifs aux événements

evenements:
  path: /evenements/accueil
  controller: App\Controller\EventsController::index

evenementId:
  path: /evenements/{id}/description
  controller: App\Controller\EventsController::show

evenementsAll:
  path: /evenements/tous
  controller: App\Controller\EventsController::all

evenementsMois:
  path: /evenements/mois
  controller: App\Controller\EventsController::month

evenementsPerso:
  path: /evenements/mes_evenements
  controller: App\Controller\EventsController::my

evenementsRegisterId:
  path: /evenements/{id}/register
  controller: App\Controller\EventsController::register

evenementsReportId:
  path: /evenements/{id}/report
  controller: App\Controller\EventsController::report

evenementsDownloadCSVId:
  path : /evenements/{id}/DownloadCSV
  controller : App\Controller\EventsController::downloadCSV

evenementsDownloadPDFId:
  path : /evenements/{id}/DownloadPDF
  controller : App\Controller\EventsController::downloadPDF

#evenementsDownloadPDF:
 # path: /evenements/{id}/dl-pdf
 # controller: App\Controller\EventsController::downloadPDF

#chemin relatif à la législation

legislation:
  path: /legislation
  controller: App\Controller\HomeController::legislation

#chemins relatifs à la boutique

boutique/accueil:
  path: /boutique/accueil
  controller: App\Controller\ShopController::index

boutique/produits:
  path: /boutique/tous-nos-produits
  controller: App\Controller\ShopController::all

boutique/categorie/habits:
  path: /boutique/habits
  controller: App\Controller\ShopController::habits

boutique/categorie/produits-IT:
  path: /boutique/produits-IT
  controller: App\Controller\ShopController::produitsIT

boutique/categorie/goodies:
  path: /boutique/goodies
  controller: App\Controller\ShopController::goodies

boutique/categorie/reductions:
  path: /boutique/reduction
  controller: App\Controller\ShopController::reduction

administration:
  path: /administration
  controller: App\Controller\Admin\AdminHomeController::index

boutique/ID:
  path: boutique/{slug}-{ID}/description
  controller: App\Controller\ShopController::show
  requirements:
    slug: '[a-z0-9\-]*'

#chemins relatifs à la partie admin - event

adminEventsHome:
  path: /administration/evenements
  controller: App\Controller\Admin\AdminEventsController::index

adminEventsAdd:
  path: /administration/evenements/add
  controller: App\Controller\Admin\AdminEventsController::add

adminEventsEdit:
  path: /administration/evenements/edit/{id}
  controller: App\Controller\Admin\AdminEventsController::edit

adminEventsDelete:
  path: /administration/evenements/delete/{id}
  controller: App\Controller\Admin\AdminEventsController::delete

adminEventsSearch:
  path: /administration/evenements/{search}
  controller: App\Controller\Admin\AdminEventsController::search

#chemins relatifs à la partie admin - catégorie

adminCategoryHome:
  path: /administration/categories
  controller: App\Controller\Admin\AdminCategoryController::index

adminCategoryAdd:
  path: /administration/categories
  controller: App\Controller\Admin\AdminCategoryController::add

adminCategoryEdit:
  path: /administration/categories/edit/{id}
  controller: App\Controller\Admin\AdminCategoryController::edit

adminCategoryDelete:
  path: /administration/categories/delete/{id}
  controller: App\Controller\Admin\AdminCategoryController::delete

#chemins relatifs à la partie admin - boutique

adminProductsHome:
  path: /administration/produits
  controller: App\Controller\Admin\AdminProductsController::index

adminProductsAdd:
  path: /administration/produits/add
  controller: App\Controller\Admin\AdminProductsController::add

adminProductsEdit:
  path: /administration/produits/edit/{id}
  controller: App\Controller\Admin\AdminProductsController::edit

adminProductsDelete:
  path: /administration/produits/delete/{id}
  controller: App\Controller\Admin\AdminProductsController::delete

adminProductsSearch:
  path: /administration/produits/{search}
  controller: App\Controller\Admin\AdminProductsController::search

#chemin relatif aux images

photos:
  path: /photos
  controller: App\Controller\PhotosController::index

photosId:
  path: /photos/{id}/description
  controller: App\Controller\PhotosController::show

photosReportId:
  path: /photos/{id}/report
  controller: App\Controller\PhotosController::report

security_connexion:
  path: /connexion
  controller: App\Controller\SecurityController::login

security_inscription:
  path: /inscription
  controller: App\Controller\SecurityController::inscription

security_deconnexion:
  path: /deconnexion
  controller: App\Controller\SecurityController::deconnexion

#chemin relatif aux commentaires

commentsReportId:
  path: /commentaire/{id}/report
  controller: App\Controller\CommentController::report