<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5OzY0ER\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5OzY0ER/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5OzY0ER.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5OzY0ER\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5OzY0ER\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5OzY0ER',
    'container.build_id' => '81c3c675',
    'container.build_time' => 1573065376,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5OzY0ER');
